languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 2
rtl = false

title = "Mans Ziesel"
# logo = "img/Mans_Ziesel_Portrait.jpg"
description = "Website of Mans Ziesel"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
   name = "Mans Ziesel"
   image = "img/Mans_Ziesel_Portrait.jpg"
   headline = "Student at ROC van Twente"
   # bio = "A little bit about you"
   links = [
#     { email = "mailto:mans@mziesel.com" },
     { github = "https://github.com/mansziesel" },
     { linkedin = "https://linkedin.com/in/mansziesel" },
   ]
