languageCode = "nl"
languageName = "Nederlands"
displayName = "NL"
isoCode = "nl"
weight = 1
rtl = false

title = "Mans Ziesel"
# logo = "img/Mans_Ziesel_Portrait.jpg"
description = "Website van Mans Ziesel"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
   name = "Mans Ziesel"
   image = "img/Mans_Ziesel_Portrait.jpg"
   headline = "ICT'er & student bij ROC van Twente"
   # bio = "A little bit about you"
   links = [
     { email = "mailto:mans@mziesel.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://mansziesel.blogspot.com/" },
#     { codepen = "https://codepen.io/mansziesel" },
#     { dev = "https://dev.to/mansziesel" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/mansziesel" },
#     { facebook = "https://facebook.com/mansziesel" },
#     { flickr = "https://www.flickr.com/photos/mansziesel/" },
#     { foursquare = "https://foursquare.com/mansziesel" },
     { github = "https://github.com/mansziesel" },
#     { gitlab = "https://gitlab.com/mansziesel" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://mansziesel.hashnode.dev" },
#     { instagram = "https://instagram.com/mansziesel" },
#     { keybase = "https://keybase.io/mansziesel" },
#     { kickstarter = "https://www.kickstarter.com/profile/mansziesel" },
#     { lastfm = "https://lastfm.com/user/mansziesel" },
     { linkedin = "https://linkedin.com/in/mansziesel" },
#     { mastodon = "https://mastodon.instance/@mansziesel" },
#     { medium = "https://medium.com/mansziesel" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/mansziesel" },
#     { pinterest = "https://pinterest.com/mansziesel" },
#     { reddit = "https://reddit.com/user/mansziesel" },
#     { researchgate = "https://www.researchgate.net/profile/mansziesel" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/mansziesel" },
#     { soundcloud = "https://soundcloud.com/mansziesel" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/mansziesel" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/mansziesel" },
#     { tiktok = "https://tiktok.com/@mansziesel" },
#     { tumblr = "https://mansziesel.tumblr.com" },
#     { twitch = "https://twitch.tv/mansziesel" },
#     { twitter = "https://twitter.com/mansziesel" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/mansziesel" },
#     { ko-fi = "https://ko-fi.com/mansziesel" },
   ]
